name: Windows Desktop Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: 🎉 Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows desktop app
        run: flutter build windows --release

      - name: Create build directory
        run: mkdir -p build/windows/Release

      - name: Move app to build directory
        run: move build\windows\runner\Release\Runner.exe build\windows\Release\

      - name: Zip the app
        run: powershell Compress-Archive -Path build\windows\Release\Runner.exe -DestinationPath build\windows\Release\MyDesktopApp.zip

      - name: Upload app to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/Release/MyDesktopApp.zip
          tag: v1.0
          overwrite: true
          body: "This is the first release"
